### PR TITLE
fix(AppNodeSchema): Fix type of Git metadata

### LINKED ISSUE #55: Creating a new status node without Git revision fails
On 0d2b8e4 creating a status node without a git revision fails because the node form validation fails. 

After a revision was selected and it is cleared again, the form can be submitted

Image

### PR DESCRIPTION
**Pull request by jonasehrlich**
`PendingNodeData::defaultRev` is defined as `GitMetadata | undefined` while the `AppNodeSchema` defined it as `nullable`. When creating a node without setting a Git revision this leads to a form validation error. This change aligns the `AppNodeSchema.git` type as `optional`.

Closes #55

### CODE REVIEW

File: frontend/src/components/async-combobox.tsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ import { Button } from "./ui/button";
 
 interface AsyncComboboxProps<ItemType> {
   /** Current value of the dropdown */
-  value: ItemType | null;
+  value?: ItemType | null;
```
Comment (TobTheRock) [inline frontend/src/components/async-combobox.tsx:24]: Ok for mei was generally wondering about the best style in such cases.

So now the type is ItemType | undefined | null
. Is there any advantage to have it nullable?
Or should we just stick to `value?: ItemType` . also in all ither places in the code

Comment (jonasehrlich) [reply frontend/src/components/async-combobox.tsx:24]: The problem is, that `PendingNodeData.defaultRev` is `GitMetadata | undefined`, while `EditNodeData<"statusNode", StatusNodeData>.git` is `GitMetadata | null`. And for both cases the types are correct in my opinion as `null` is the intentional absence of any object value .

In my opinion we should rather go to `GitMetadata | null` everywhere, but that's also related to #56 etc
