### PR TITLE
Fix root node behavior

### LINKED ISSUE #28: Fix root node behavior
The initial root status node fours not have a target handle. But it also should:
- [x] Not be deletable by node header menu
- [x] Not be deletable using the `Backspace` key
- [x] Not be removable by undo [see store.ts](https://github.com/jonasehrlich/debug-flow/pull/34/files#diff-e942e3d33264a50176002074e14efff33e268d5e21cb9abe3c49b164bbbcaa4bR26-R29) in #34 

If the root node is removed we end up with an unrecoverable state. See [NodeProps::deletable](https://reactflow.dev/api-reference/types/node-props#deletable)

### PR DESCRIPTION
**Pull request by jonasehrlich**
* Change `hasTargetHandle` prop to `isRootNode`
* Do not add target handler for root node
* Set `deletable` to false when adding a node and there are no nodes in the flow

Closes #28

### CODE REVIEW

File: frontend/src/types/nodes.ts [hunk 1]
```diff
@@ -36,8 +36,8 @@ export type StatusNodeData = {
   state: StatusNodeState;
   description: string;
   git: GitMetadata | null;
-  /// If set to true, the node gets a target handle, this is set for the initial node in a flow
-  hasTargetHandle: boolean;
+  /// If set to true, the node does not get a target handle, and is not deletable
+  isRootNode: boolean;
   // TODO: Add ticket reference
```
Comment (TobTheRock) [inline frontend/src/types/nodes.ts:41]: Nit: maybe boyscout and remove this floating comment?

**Review by TobTheRock — APPROVED** [review]
